### ISSUE TITLE
File size is determined incorrectly

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/Arqiver#6] opened 2019-01-02 13:14 UTC
Hello. I'm running Arqiver on Mac OS
In some archives file size is set to 0 for all files like on the attached screenshot while on others everything is okay.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/19782228/50593328-59cb3280-0eb1-11e9-9ce3-94a5bc125cde.png">
You can find the problematic archive in the attachment
[BullsAndCows.zip](https://github.com/tsujan/Arqiver/files/2720811/BullsAndCows.zip)
Both archives are extracted correctly. It is so selective only when it comes to file sizes

**Comment by shlyakpavel** [comment] 2019-01-02 13:21
The same archive is okay on Linux
<img width="623" alt="image" src="https://user-images.githubusercontent.com/19782228/50593657-99dee500-0eb2-11e9-8a7e-38356b49c3be.png">
BUT the other archives I could reach were okay on Mac as well as on Linux.
Can you please leave some recommendations on debugging this?

**Comment by tsujan** [comment] 2019-01-02 17:24
Your attached archive is opened correctly on Linux. This screenshot is taken on Manjaro (ignore the Mac-like Kvantum style):

![arqiver](https://user-images.githubusercontent.com/981076/50603589-44193580-0ed0-11e9-8e83-dfed17bc09bb.png)

The most important library, based on which Arqiver works, is Linux's `libarchive`. My guess: `libarchive` is not the same on Mac

**Comment by tsujan** [comment] 2019-01-02 17:51
Arqiver is surely not free of bugs (actually, a week ago, I found a bug, which I'll fix later) but I think if this was a problem in Arqiver, it should happen on Linux too. So, the problem is either in Mac's `libarchive` or in Arqiver's Mac support (which is missing. of course).

In `backends.cpp`, you can see these lines:
```c++
#ifdef Q_OS_LINUX
#define TAR_CMD "bsdtar"
#else
#define TAR_CMD "tar"
#endif
```
They are for Linux and *BSD. There's no Mac support at all.

> It needs debugging. What should I start with?

I don't think there's a way: it isn't a crash with a backtrace and I don't think `gdb arqiver` could reveal anything. If the problem was reproducible here, I could investigate the code.

**Comment by tsujan** [comment] 2019-01-02 17:56
BTW, your second screenshot shows what happens when the icon set is poor. I might add a workaround for that later, although the problem isn't in the app.

**Comment by tsujan** [comment] 2019-01-02 18:05
Update:

Arqiver should use `tar` with Mac, while it uses `bsdtar` on Linux (which is like `tar` on BSD). So, it's just by chance that it works with some archives in Mac ;)

I close this because the reported behavior is expected. Tell me if you could find a good Mac support (but I think, in the case of Arqiver, it may be very difficult).

**Closed by tsujan** 2019-01-02 18:05 UTC

**Comment by shlyakpavel** [comment] 2019-01-02 18:57
@tsujan Mac shares the same bsdtar with bsd
<img width="417" alt="image" src="https://user-images.githubusercontent.com/19782228/50607152-aaf31a80-0ee1-11e9-9511-a3f6dfcfe58c.png">
I believe the problem is more general

**Comment by shlyakpavel** [comment] 2019-01-02 19:06
> They are for Linux and *BSD. There's no Mac support at all.

That's what I wanna bring here
> I don't think there's a way: it isn't a crash with a backtrace

It is possible to track what functions return and current variable status. I just need to know where to put breakpoints

**Comment by shlyakpavel** [comment] 2019-01-02 19:23
<img width="662" alt="image" src="https://user-images.githubusercontent.com/19782228/50607872-34a3e780-0ee4-11e9-8818-a9a53a9070b5.png">
I've made a breakpoint on void Backend::parseLines (QStringList& lines) 
It looks like wrong size is reported by bsdtar -tv -f path:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/19782228/50608169-33bf8580-0ee5-11e9-98db-3e2b73d99ff6.png">
So the only idea I have of supporting Mac is bringing new version of lib archive into the package
